# Generated by Django 3.0.7 on 2020-07-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=300)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
