# Generated by Django 3.0.7 on 2020-07-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(default='', max_length=70)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=150)),
                ('address2', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField(default=0)),
            ],
        ),
    ]
