# Generated by Django 3.0.7 on 2020-07-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200713_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='SubCategory',
            field=models.CharField(default='', max_length=60),
        ),
    ]
